/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as StatusRouteImport } from "./routes/status"
import { Route as ResetPasswordRouteImport } from "./routes/reset-password"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as TurretIndexRouteImport } from "./routes/turret/index"
import { Route as ResetPasswordTokenRouteImport } from "./routes/reset-password/$token"
import { Route as TurretSessionsSessionIdRouteImport } from "./routes/turret/sessions/$sessionId"

const StatusRoute = StatusRouteImport.update({
  id: "/status",
  path: "/status",
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: "/reset-password",
  path: "/reset-password",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const TurretIndexRoute = TurretIndexRouteImport.update({
  id: "/turret/",
  path: "/turret/",
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordTokenRoute = ResetPasswordTokenRouteImport.update({
  id: "/$token",
  path: "/$token",
  getParentRoute: () => ResetPasswordRoute,
} as any)
const TurretSessionsSessionIdRoute = TurretSessionsSessionIdRouteImport.update({
  id: "/turret/sessions/$sessionId",
  path: "/turret/sessions/$sessionId",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/login": typeof LoginRoute
  "/reset-password": typeof ResetPasswordRouteWithChildren
  "/status": typeof StatusRoute
  "/reset-password/$token": typeof ResetPasswordTokenRoute
  "/turret/": typeof TurretIndexRoute
  "/turret/sessions/$sessionId": typeof TurretSessionsSessionIdRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/login": typeof LoginRoute
  "/reset-password": typeof ResetPasswordRouteWithChildren
  "/status": typeof StatusRoute
  "/reset-password/$token": typeof ResetPasswordTokenRoute
  "/turret": typeof TurretIndexRoute
  "/turret/sessions/$sessionId": typeof TurretSessionsSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/login": typeof LoginRoute
  "/reset-password": typeof ResetPasswordRouteWithChildren
  "/status": typeof StatusRoute
  "/reset-password/$token": typeof ResetPasswordTokenRoute
  "/turret/": typeof TurretIndexRoute
  "/turret/sessions/$sessionId": typeof TurretSessionsSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/login"
    | "/reset-password"
    | "/status"
    | "/reset-password/$token"
    | "/turret/"
    | "/turret/sessions/$sessionId"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/login"
    | "/reset-password"
    | "/status"
    | "/reset-password/$token"
    | "/turret"
    | "/turret/sessions/$sessionId"
  id:
    | "__root__"
    | "/"
    | "/login"
    | "/reset-password"
    | "/status"
    | "/reset-password/$token"
    | "/turret/"
    | "/turret/sessions/$sessionId"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRouteWithChildren
  StatusRoute: typeof StatusRoute
  TurretIndexRoute: typeof TurretIndexRoute
  TurretSessionsSessionIdRoute: typeof TurretSessionsSessionIdRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/status": {
      id: "/status"
      path: "/status"
      fullPath: "/status"
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/reset-password": {
      id: "/reset-password"
      path: "/reset-password"
      fullPath: "/reset-password"
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/turret/": {
      id: "/turret/"
      path: "/turret"
      fullPath: "/turret/"
      preLoaderRoute: typeof TurretIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/reset-password/$token": {
      id: "/reset-password/$token"
      path: "/$token"
      fullPath: "/reset-password/$token"
      preLoaderRoute: typeof ResetPasswordTokenRouteImport
      parentRoute: typeof ResetPasswordRoute
    }
    "/turret/sessions/$sessionId": {
      id: "/turret/sessions/$sessionId"
      path: "/turret/sessions/$sessionId"
      fullPath: "/turret/sessions/$sessionId"
      preLoaderRoute: typeof TurretSessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ResetPasswordRouteChildren {
  ResetPasswordTokenRoute: typeof ResetPasswordTokenRoute
}

const ResetPasswordRouteChildren: ResetPasswordRouteChildren = {
  ResetPasswordTokenRoute: ResetPasswordTokenRoute,
}

const ResetPasswordRouteWithChildren = ResetPasswordRoute._addFileChildren(
  ResetPasswordRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRouteWithChildren,
  StatusRoute: StatusRoute,
  TurretIndexRoute: TurretIndexRoute,
  TurretSessionsSessionIdRoute: TurretSessionsSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
